api/_main_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    #
    path("auth/", include("auth_app.urls"), 
    ),
    path("stocks/", include("stocks_app.urls")),
    path("", include("public_app.urls"))

]

api/auth_app/urls.py
from django.urls import path
from .views import sign_in, sign_up



app_name = "auth_app"

urlpatterns = [
    path("signin", sign_in, name="sign_in"),
    path("signup", sign_up, name="sign_up"),
]

api/public_app/urls.py
from django.urls import path
from .views import landing

urlpatterns = [
    path("", landing)
]

api/stocks_app/urls.py
from django.urls import path
from .views import stocks, imports, exports, stock, export_add

app_name = "stocks_app"

urlpatterns  =[
    path("", stocks, name="stocks"),
    path("<int:pk>", stock, name="stock"),
    #
    path("imports", imports, name="imports"),
    path("exports", exports, name="exports"),
    path("exports/add", export_add, name="export_add"),

]

api/auth_app/models.py
from django.db import models
from django.utils.crypto import get_random_string

# user


class Wilaya(models.Model):
    code = models.IntegerField()
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.code} - {self.name}"


class CustomUser(models.Model):
    class UserType(models.TextChoices):
        CUSTOMER = "C", "Customer"
        OWNER = "O", "Owner"
        GUEST = "G", "Guest"

    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=13, null=True)

    password = models.CharField(null=True, max_length=64)

    last_logged = models.DateTimeField(auto_now=True)

    user_type = models.CharField(
        max_length=20,
        choices=UserType.choices,
        default=UserType.CUSTOMER,
    )

    name = models.CharField(null=True, max_length=64)
    surname = models.CharField(null=True, max_length=64)
    wil = models.ForeignKey(Wilaya, models.CASCADE, null=True)

    def is_auth(email, pwd):
        return CustomUser.objects.filter(
            email=email, password=make_password(pwd)
        ).exists()

    def __str__(self):
        return self.email


# session


class CustomSessionManager(models.Manager):
    def new_session(self, customer=None):
        # generate a unique session
        token = get_random_string(32)
        while self.filter(token=token).exists():
            token = get_random_string(32)
        #
        obj = self.model(customer=customer, token=token)
        obj.save()

        return obj

    def get_user_from_request(self, request_query):
        user = None
        try:
            # get the session first
            session = self.get_session_from_request(request_query)
            if session:
                user = session.customer
        except:
            pass

        return user

    def get_session_from_request(self, request_query):
        session = None
        try:
            # get the session first
            session = self.get(token=request_query["token"])
        except:
            pass

        return session

    def is_auth(self, request_query):
        auth = False

        try:
            auth = self.filter(token=request_query["token"]).exists()
        except:
            pass

        return auth


class CustomerSession(models.Model):
    customer = models.ForeignKey(CustomUser, models.CASCADE, null=True)
    token = models.CharField(max_length=32)
    created = models.DateTimeField(auto_now=True)

    objects = CustomSessionManager()

api/public_app/models.py
from django.db import models

# Create your models here.

api/stocks_app/models.py
from django.db import models

class Stock(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=100)
    quantity = models.IntegerField()
    unit = models.CharField(max_length=50)
    country_of_origin = models.CharField(max_length=100)
    exported_to = models.JSONField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_value = models.DecimalField(max_digits=15, decimal_places=2)
    description = models.TextField()
    img = models.URLField(max_length=500, blank=True, null=True)  # Add image URL field here

    def __str__(self):
        return self.name

api/auth_app/forms.py
from django import forms
from .models import CustomUser

# from django.contrib.auth.hashers import make_password


class SignInForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", "password"]

    email = forms.CharField(
        max_length=32,
        widget=forms.EmailInput(attrs={"placeholder": "enter your email"}),
    )
    password = forms.CharField(
        max_length=32, widget=forms.PasswordInput(attrs={"placeholder": "password"})
    )

    def clean(self):

        email = self.cleaned_data.get("email")
        if not CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError({"email": ["unexsiting account"]})

        password = self.cleaned_data.get("password")
        if not CustomUser.objects.filter(password=password).exists():
            raise forms.ValidationError({"password": ["wrong password"]})

    def get_user(self):
        return CustomUser.objects.get(email=self.cleaned_data.get("email"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", "phone_number", "password"]

    email = forms.CharField(
        max_length=32,
        widget=forms.EmailInput(attrs={"placeholder": "enter your email"}),
    )
    password = forms.CharField(
        max_length=32, widget=forms.PasswordInput(attrs={"placeholder": "password"})
    )

    phone_number = forms.CharField(
        max_length=13,
        widget=forms.TextInput(attrs={"placeholder": "enter your phone number"}),
    )

    confirm_password = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(attrs={"placeholder": "confirm your password"}),
    )
    #

    def clean(self):

        email = self.cleaned_data.get("email")
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError({"email": ["used email"]})

        phone_number = self.cleaned_data.get("phone_number")
        if CustomUser.objects.filter(phone_number=phone_number).exists():
            raise forms.ValidationError({"email": ["used phone number"]})

        # same password
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                {
                    "password": ["passwords must be indentical"],
                    "confirm_password": ["passwords must be indentical"],
                }
            )

    def save(self, commit=True):
        # Create a new CustomUser instance
        user = super().save(commit=False)
        user.password = user.password
        # You can perform additional actions here if needed
        if commit:
            user.save()

        return user

api/auth_app/views.py
from django.shortcuts import render




def sign_in(request):
    return render(request, "auth_app/signin.html", {})

def sign_up(request):
    return render(request, "auth_app/signup.html", {})

api/public_app/views.py
from django.shortcuts import render

def landing(request):
    return render(request, "public_app/landing.html", {})

api/stocks_app/views.py
from django.shortcuts import render
from .models import Stock
# Create your views here.



def stocks(request):
    stks = Stock.objects.all()

    return render(request, "stocks_app/stocks.html", {"stks":stks})



def imports(request):
    stks = Stock.objects.all()

    return render(request, "stocks_app/imports.html", {"stks":stks})



def exports(request):
    stks = Stock.objects.all()

    return render(request, "stocks_app/exports.html", {"stks":stks})


def export_add(request):
    return render(request, "stocks_app/export_add.html", {})


def stock(request, pk):
    itm = Stock.objects.get(id=pk)
    stks = Stock.objects.all()

    return render(request, "stocks_app/stock.html", {
        "itm":itm,
        "smlrs":stks})

api/templates/auth_app/auth_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>
    TradeFusion
  </title>

  {% load static %}


  <link rel="shortcut icon" href="{% static 'assets/images/logos/logo1.png' %}" type="image/x-icon" />

  <link rel="stylesheet" href="{% static 'assets/fonts/zonaPro/zonaPro.css' %}" />
  <link rel="stylesheet" href="{% static 'widgets/theme_light.css' %}" />

  <link rel="stylesheet" href="{% static 'widgets/section/section.css' %}" />
  <link rel="stylesheet" href="{% static 'widgets/button/button.css' %}" />
  <link rel="stylesheet" href="{% static 'widgets/form/form.css' %}" />


  <link rel="stylesheet" href="{% static 'widgets/app_base/app_base.css' %}" />

  <link rel="stylesheet" href="{% static 'auth_app/auth_base.css' %}" />
</head>

<body>
  <div id="left">
    <!--<img src="{% static 'assets/images/bgs/auth.png' %}" alt="" id="bg">-->


    <div class="section">
      <div class="section_content" id="welcome_content">
        <img src="{% static 'assets/images/logos/logo1.png' %}" alt="" id="logo">
        <div>
          <h2>Welcome to</h2>
          <h1>TradeFusion</h1>
        </div>
      </div>
    </div>


  </div>

  <div id="right">

    <div class="section" id="form_wrapper">
      <div class="section_title">
        <h1>
          {% block title %}{% endblock %}
        </h1>


      </div>
      <div class="section_content">
        <form method="post" action="{% url 'stocks_app:stocks' %}">
          {% csrf_token %}

          {% block frm %}
          {% endblock %}



          <button type="text" onclick="document.location.href=`{% url 'stocks_app:stocks' %}`">{% block btn%}{% endblock%}</button>

        </form>

        {% block redirect %}{% endblock %}

      </div>
    </div>





  </div>
</body>

</html>

api/templates/auth_app/signin.html
{% extends 'auth_app/auth_base.html' %}



{% block title%} SignIn {% endblock%} 
{% block btn%} Sign In {% endblock%} 


{% block frm %}
<div class="section input_section" id="{{field.label}}">
    <div class="section_title input_tag">
        Email
    </div>
    <div class="section_content">
        <input type="email" name="" id="" placeholder="Email">
    </div>
</div>

<div class="section input_section" id="{{field.label}}">
    <div class="section_title input_tag">
        Password
    </div>
    <div class="section_content">
        <input type="password" name="" id="" placeholder="Password">
    </div>
</div>
{% endblock %}

{% block redirect %}
<a href="{% url 'auth_app:sign_up' %}">I don't have an account</a>
{% endblock %}

api/templates/auth_app/signup.html
{% extends 'auth_app/auth_base.html' %}



{% block title%} SignUp {% endblock%}
{% block btn%} Sign Up & Verify {% endblock%}




{% block frm %}


<!--
<div class="section borders overflow" style="margin: var(--sz4);">
    <div class="section_title">
        <h2> Authorizations & Certifications</h2>
        <button type="button">Add +</button>
    </div>
    <div class="section_content">
        <table>
            <thead>
                <tr>
                    <th>File</th>
                    <th>Size</th>
                    <th></th>                                
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>declaration1.pdf</td>
                    <td>50K</td>
                    <td>x</td>
                </tr>
                <tr>
                    <td>declaration2.pdf</td>
                    <td>50K</td>
                    <td>x</td>
                </tr>
                <tr>
                    <td>declaration3.pdf</td>
                    <td>50K</td>
                    <td>x</td>
                </tr>
            </tbody>
        </table>


    </div>
</div>
-->

<div class="section input_section">
    <div class="section_title input_tag">
        Name
    </div>
    <div class="section_content">
        <input type="text" placeholder="Name">
    </div>
</div>

<div class="section input_section">
    <div class="section_title input_tag">
        Surname
    </div>
    <div class="section_content">
        <input type="text" placeholder="Surname">
    </div>
</div>

<div class="section input_section">
    <div class="section_title input_tag">
        Address
    </div>
    <div class="section_content">
        <input type="text" placeholder="Address">
    </div>
</div>

<div class="section input_section">
    <div class="section_title input_tag">
        NIN
    </div>
    <div class="section_content">
        <input type="text" placeholder="NIN">
    </div>
</div>

<div class="section input_section">
    <div class="section_title input_tag">
        BIC
    </div>
    <div class="section_content">
        <input type="text" placeholder="BIC">
    </div>
</div>

<div class="section input_section">
    <div class="section_title input_tag">
        IBAN
    </div>
    <div class="section_content">
        <input type="text" placeholder="IBAN">
    </div>
</div>


<div class="section input_section">
    <div class="section_title input_tag">
        Email
    </div>
    <div class="section_content">
        <input type="email" placeholder="Email">
    </div>
</div>

<div class="section input_section">
    <div class="section_title input_tag">
        Phone Number
    </div>
    <div class="section_content">
        <input type="tel" placeholder="Phone Number">
    </div>
</div>


<div class="section borders" style="margin-top: var(--sz4);">
    <div class="section_title">
        <h2>Authorizations & Certifications</h2>
    </div>

    <div class="section_content">
        <div class="section input_section">
            <div class="section_title input_tag">
                Import License
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Certificate of Conformity
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Trade Register (Registre de commerce)
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Tax Identifier (Carte fiscale)
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Commercial Invoice
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Mandate for the customs broker
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Border Inspection Documents
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Special Licenses (if applicable)
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Certificate of Origin
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Packing List
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

        <div class="section input_section">
            <div class="section_title input_tag">
                Detailed Note (itemized list of contents)
            </div>
            <div class="section_content">
                <input type="text" placeholder="UPLOAD CERTIFICATION PDF">
            </div>
        </div>

    </div>
</div>

{% endblock %}


{% block redirect %}
<a href="{% url 'auth_app:sign_in' %}">I have an account</a>
{% endblock %}

api/templates/public_app/landing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TradeFusion - Your Trusted Logistics Partner</title>

    {% load static %}

    <link rel="shortcut icon" href="{% static 'assets/images/logos/logo1.png' %}" type="image/x-icon" />

    <link rel="stylesheet" href="{% static 'assets/fonts/zonaPro/zonaPro.css' %}" />
    <link rel="stylesheet" id="theme_css" href="{% static 'widgets/theme_light.css' %}" />
    <link rel="stylesheet" href="{% static 'widgets/app_base/app_base.css' %}" />
    <link rel="stylesheet" href="{% static 'widgets/app_base/page_base.css' %}" />
    <link rel="stylesheet" href="{% static 'widgets/button/button.css' %}">

    <link rel="stylesheet" href="{% static 'widgets/section/section.css' %}">
    <link rel="stylesheet" href="{% static 'public_app/landing.css' %}">

</head>

<body>
    <img id="bg" src="{% static '/assets/images/bgs/header.png' %}" alt="">

    <div id="navbar">
        <img src="{% static '/assets/images/logos/svg/logo2.svg' %}" id="logo"></img>

        <div id="links">
            <a href="#services">Services</a>
            <a href="#why">Why Us</a>
            <a href="#faq">FAQ</a>
            <a href="#contact">Contact</a>
        </div>

        <button>Sign In</button>
        <button>Sign Up</button>
    </div>

    <div id="content">

        <div class="section main" id="home">
            <div class="section_content">
                <h1>Welcome to TradeFusion</h1>
                <h2>our trusted partner in efficient, reliable, and timely delivery services</h2>
            </div>
        </div>

        <div class="section main" id="services">
            <div class="section_title">
                <h1>Our Services</h1>
            </div>
            <div class="section_content grid3">
                <div class="section card">
                    <div class="section_title">
                        <h2>TITLE</h2>
                    </div>
                    <div class="section_content">
                        <p>CONTENT</p>
                    </div>
                </div>
                <div class="section card">
                    <div class="section_title">
                        <h2>TITLE</h2>
                    </div>
                    <div class="section_content">
                        <p>CONTENT</p>
                    </div>
                </div>
                <div class="section card">
                    <div class="section_title">
                        <h2>TITLE</h2>
                    </div>
                    <div class="section_content">
                        <p>CONTENT</p>
                    </div>
                </div>
                <div class="section card">
                    <div class="section_title">
                        <h2>TITLE</h2>
                    </div>
                    <div class="section_content">
                        <p>CONTENT</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="section main" id="why">
            <div class="section_title main">
                <h1>Why Us?</h1>
            </div>
            <div class="section_content"></div>
        </div>


        <div class="section main" id="faq">
            <div class="section_title main">
                <h1>Frequently Asker Questions</h1>
            </div>
            <div class="section_content"></div>
        </div>

        <div class="section main" id="contact">
            <div class="section_title main">
                <h1>Contact Us</h1>
            </div>
            <div class="section_content"></div>
        </div>

    </div>
</body>

</html>

api/templates/widgets/app_base/app_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>TradeFusion</title>

  {% load static %}
  {% load i18n %}

  <link rel="shortcut icon" href="{% static 'assets/images/logos/logo1.png' %}" type="image/x-icon" />

  <link rel="stylesheet" href="{% static 'assets/fonts/zonaPro/zonaPro.css' %}" />
  <link rel="stylesheet" id="theme_css" href="{% static 'widgets/theme_light.css' %}" />
  <link rel="stylesheet" href="{% static 'widgets/app_base/app_base.css' %}" />
  <link rel="stylesheet" href="{% static 'widgets/app_base/page_base.css' %}" />
</head>

<body>
  <div id="left">{% block nav_panel %}{% endblock %}</div>
  <div id="right">
    <div class="page_base">
      <link rel="stylesheet" href="{% static 'widgets/section/section.css' %}" />
      <link rel="stylesheet" href="{% static 'widgets/button/button.css' %}" />

      <div class="section" id="page_section">
        <div class="section_title" id="page_title">
          <h1>{% block page_title %}{% endblock %}</h1>
        </div>


        <div class="section_content">
          {% block page_body %} {% endblock %}
        </div>
      </div>
    </div>

    {% include 'widgets/footer/footer.html' %}

  </div>

  {% include 'widgets/floating_icon/floating_icon.html' %}

  <!--
  <script src="{% static 'scripts/theme.js' %}"></script>
  <script>
    const LIGHT = "{% static 'widgets/theme_light.css' %}";
    const DARK = "{% static 'widgets/theme_dark.css' %}";
    const CURRENT_THEME = localStorage.getItem('theme')
    //  


    toggleButton.addEventListener('dblclick', () => {
      if (CURRENT_THEME.includes("light")) {
        themeStyle.href = DARK;
        localStorage.setItem('theme', DARK);
        //
      } else {
        themeStyle.href = LIGHT;
        localStorage.setItem('theme', LIGHT);
        //
      }
    });


    toggleButton.addEventListener("click")
  </script>
-->

</body>

</html>

api/templates/widgets/app_base/app_base_client.html
{% extends 'widgets/app_base/app_base.html' %}

{% block nav_panel %}
{% include 'widgets/nav_panel/nav_panel_client.html' %}
{% include 'widgets/client_navbar/client_navbar.html' %}
{% endblock %}

api/templates/widgets/app_base/app_base_owner.html
{% extends 'widgets/app_base/app_base.html' %}

{% block nav_panel %}
{% include 'widgets/nav_panel/nav_panel_owner.html' %}
{% endblock %}

api/templates/widgets/categ_card/categ_card.html
<div class="categ_card">
    {% load static %}
    <link rel="stylesheet" href="{% static 'widgets/categ_card/categ_card.css' %}">
    <div class="img">
        {% if categ.img %}
        <img src="{{categ.img}}" alt="">
        {% endif %}
    </div>

    <h2>{{categ}}</h2>


    <a href="{% url 'client_app:categ' pk=categ.pk %}"></a>

</div>

api/templates/widgets/footer/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/footer/footer.css' %}">


<div class='footer'>

    <div id="row">
        <div id="logo">
            {% include 'widgets/logo/logo2_0.html' %}
        </div>


        <div class="section">
            <div class="section_content grid2">

                <!--
                <div class="section">
                    <div class="section_title">
                        <h3>Developer info</h3>
                    </div>
                    <div class="section_content">
                        <p>+213 XXX XX XX XX</p>
                        <p>XXXXXXX@gmail.com</p>
                    </div>
                </div>
            -->

                <div class="section">
                    <div class="section_title">
                        <h3>Contact Us</h3>
                    </div>
                    <div class="section_content">
                        <p>+213 XXX XX XX XX</p>
                        <p>+213 XXX XX XX XX</p>
                        <p>instagram.com/XXXXX</p>
                        <p>XXXXXXX@gmail.com</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a id="me" href="https://github.com/zaqks">Designed and Developped By zaqks</a>

    <div id="langs">
        <a style="cursor: pointer;" id="EN">en</a>
        <a style="cursor: pointer;" id="FR">fr</a>
    </div>

    <script src="{% static 'scripts/langs.js' %}"></script>

</div>

api/templates/widgets/form/form.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/form/form.css' %}">


<div class="section input_section" id="{{field.label}}">
    <div class="section_title input_tag">
        {{ field.label }}
    </div>
    <div class="section_content">
        {{ field }}        

        {% for error in field.errors %}
        <div class="input_error">
            {{ error }}
        </div>
        {% endfor %}

    </div>


</div>

api/templates/widgets/item_card/item_card_f.html
<div class='section item_card full borders'>
    {% load static %}
    <link rel="stylesheet" href="{% static 'widgets/item_card/item_card_v.css' %}">
    <link rel="stylesheet" href="{% static 'widgets/item_card/item_card_f.css' %}">

    {% block shop_url %}
    {% endblock %}

    <div class="section_title">
        <img src="{{itm.images.first}}">
    </div>

    <div class="section_content">
        <a href="{% url 'client_app:item' pk=itm.pk %}"></a>

        <h2>{{itm.price|floatformat:0}} {{currency}}</h2>

        <h1>{{itm.name}}</h1>




        <!--{{itm.images.all}}-->
    </div>
</div>

api/templates/widgets/item_card/item_card_v.html
{% load static %}

<link rel="stylesheet" href="{% static 'widgets/item_card/item_card_v.css' %}">

<div class='section item_card borders'>
    {% block shop_url %}
    {% endblock %}

    <div class="section_title">
        <img src="{{itm.img}}">
    </div>

    <div class="section_content">

        <h3>{{itm.name}}</h3>
        <h4>{{itm.category}}</h4>

        <div class="row">            
            <h2>{{itm.total_value|floatformat:0}} {{currency}}</h2>
        </div>

        <!--{{itm.images.all}}-->
    </div>
</div>

api/templates/widgets/item_card/item_card_v_client.html
{% extends 'widgets/item_card/item_card_v.html' %}

{% block shop_url %}
<a href="{%url 'stocks_app:stock' pk=itm.pk %}"></a>
{% endblock %}

api/templates/widgets/item_card/item_card_v_owner.html
{% extends 'widgets/item_card/item_card_v.html' %}

{% block shop_url %}
<a href="{% url 'owner_app:shop_item' pk=itm.pk %}"></a>
{% endblock %}

api/templates/widgets/logo/logo2_0.html
{% load static %}


<link rel="stylesheet" href="{% static 'widgets/logo/logo.css' %}">

<div class="logo logo20" onclick="document.location.href=`{% url 'stocks_app:stocks' %}`" id="theme_toggle">
  <img src="{% static 'assets/images/logos/svg/logo2.svg' %}" alt="" />
</div>

api/templates/widgets/nav_panel/nav_panel.html
{% load static %}


<link rel="stylesheet" href="{% static 'widgets/nav_panel/nav_panel.css' %}" />
<div class="nav_panel hide" id="main_nav_panel">
  <div id="logo">{% include 'widgets/logo/logo2_0.html' %}</div>

  <script src="{% static 'widgets/nav_panel/nav_panel.js' %}"></script>

  <div id="nav_cards">
    {% block cards%}
    {% endblock %}

  </div>





  <div id="btns">
    {% if logged %}
    <a href="{% url 'auth_app:sign_in' %}">Sign Out</a>
    {% else %}

    <a href="{% url 'auth_app:sign_in' %}">Sign In</a>
    <a href="{% url 'auth_app:sign_up' %}">Sign Up</a>


    {% endif %}
  </div>
  <!--<a href="https://icons8.com">Icons By Icons8</a>-->
</div>

api/templates/widgets/nav_panel/nav_panel_client.html
{% extends 'widgets/nav_panel/nav_panel.html' %}

{% block cards %}

{% load static %}


<div class="nav_card">
  <img src="{% static 'assets/icons/home.png' %}" />
  <!--alt="home"-->
  <a href="{% url 'stocks_app:stocks' %}">Home</a>
</div>
<div class="nav_card">
  <img src="{% static 'assets/icons/shopping-cart.png'%}" />
  <!--alt="calendar--v1"-->
  <a href="{% url 'stocks_app:imports' %}">Imports</a>
</div>
<div class="nav_card">
  <img src="{% static 'assets/icons/purchase-order.png'%}" />
  <!--alt="person-male--v3"-->
  <a href="{% url 'stocks_app:exports' %}">Exports</a>
</div>

<!--
<div class="nav_card">
  <img
    src="https://img.icons8.com/ios-filled/48/767676/settings.png"
    alt="settings"
  />
  <a href="">Settings</a>
</div>
-->
<script>
  new NavPanel(["/", "/imports", "/exports"]).set_select()
</script>

{% endblock %}